slug: open-mainframe-project
landscapeMemberClasses:
   - name: Platinum Membership
     category: Platinum
   - name: End-User Membership
     category: Platinum
   - name: Silver Membership
     category: Silver
   - name: Academic Membership
     category: Academic Institution
   - name: Associate Membership
     category: Associate
project: a0941000002wBymAAE # Open Mainframe Project
landscapeMemberCategory: Open Mainframe Project Member Company
landscapefile: landscape.yml
missingcsvfile: missing.csv
landscapeProjectsCategory: Open Mainframe Project Projects
landscapeProjectsLevels:
  - level: graduated
    name: Active
  - level: incubating
    name: Incubation
  - level: sandbox
    name: Sandbox
  - level: working-group
    name: Working Group
  - level: archived
    name: Emeritus
landscapeProjectsSubcategories:
  - name: All
    category: All
projectsDefaultCrunchbase: https://www.crunchbase.com/organization/open-mainframe-project
tacAgendaProjectUrl: https://github.com/orgs/openmainframeproject/projects/21/views/1
artworkRepoUrl: "https://artwork.openmainframeproject.org/projects/{slug}"
