global:
  name: Open Mainframe Project Interactive Landscape
  short_name: Open Mainframe Project
  repo: openmainframeproject/omp-landscape
  website: https://landscape.openmainframeproject.org
  short_domain: l.openmainframeproject.org
  company_url: https://openmainframeproject.org
  email: info@openmainframeproject.org
  self: https://www.crunchbase.com/organization/open-mainframe-project
  slack_channel: T08PSQ7BQ/BMK6XTF0W/8zw5d6uPTK3K7AQ4ublHwONT
  meta:
    title: Open Mainframe Project Landscape
    fb_admin: alex.contini.94
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: '@OpenMFProject'
    google_site_verification: a2XVEjwm7VZNRuQ5wY3uDlwLXvxUzodGsIxwav3opvA
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: Open Mainframe Project Member Company
  flags:
    companies: Open Mainframe Project Member Company
twitter:
  search: landscape.openmainframeproject.org
  url: https://landscape.openmainframeproject.org
  text: Open Mainframe Project Landscape from @OpenMFProject
relation:
  label: Open Mainframe Project Relation
  url: omp
  values:
    - id: hosted
      label: Open Mainframe Project Projects
      children:
        - id: graduated
          label: Graduated Open Mainframe Projects
          prefix: OMP
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: OMP Graduated
          big_picture_color: rgb(24,54,114)
        - id: incubating
          label: Incubating Open Mainframe Projects
          prefix: OMP
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: OMP Incubating
          big_picture_color: rgb(83, 113, 189)
        - id: workinggroup
          label: Open Mainframe Project Working Group
          prefix: OMP
          tag: Working Group
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: OMP Working Group
          big_picture_color: rgb(0, 123, 233)
    - id: company
      label: Open Mainframe Project Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: Open Mainframe Project Member Products/Projects
      tag: Open Mainframe Project Member
    - id: false
      label: Non-Open Mainframe Project Member Products/Projects
      url: 'no'
membership:
  Platinum:
    name: Open Mainframe Project
    label: Platinum Member
    funding: Platinum
    is_large: true
  Silver:
    name: Open Mainframe Project
    label: Silver Member
    funding: Silver
  Academic Institution:
    name: Open Mainframe Project
    label: Academic Institution Member
    funding: Academic Institution
  Associate:
    name: Open Mainframe Project
    label: Associate Member
    funding: Associate
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>Open Mainframe Project Interactive Landscape</h1> The Open Mainframe Project landscape (<a target="_blank" href="images/landscape.png">png</a>, <a
    target="_blank" href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF
    landscape</a> and based on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://events.linuxfoundation.org/open-mainframe-summit/?utm_source=omp_landscape&utm_medium=web&utm_campaign=ompsummit20
    image: /images/info1.jpg
    title: Open Mainframe Summit 2020
presets:
  - url: /category=open-mainframe-project-member-company&format=card-mode&grouping=category
    label: Open Mainframe Project members
  - url: /category=zowe-conformant&format=card-mode&grouping=category
    label: Zowe Conformant offerings
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Open Mainframe Landscape
    title: Open Mainframe Landscape
    fullscreen_header: See the interactive landscape at l.openmainframeproject.org
    elements:
      - type: HorizontalCategory
        category: Projects
        rows: 6
        width: 800
        height: 300
        top: 0
        left: 0
        color: rgb(37,81,209)
        fit_width: false
      - type: HorizontalCategory
        category: Zowe Conformant
        rows: 6
        width: 1200
        top: 325
        height: 200
        left: 0
        color: rgb(79,121,13)
        fit_width: true
      - type: LandscapeInfo
        width: 345
        height: 200
        top: 0
        left: 815
        children:
          - type: text
            text: >
              This landscape is intended as a map to explore open source projects within the mainframe industry, and also shows the member companies of the Open
              Mainframe Project.
            top: 80
            left: 180
            right: 20
            font_size: 10
          - type: image
            image: qr.svg
            top: 70
            left: 40
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.openmainframeproject.org
            top: 150
            left: 9
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 150
            right: 180
            top: 20
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 150
            right: 10
            top: 20
            title: Open Mainframe Project Logo
  fourth:
    tab_index: 2
    url: open-source
    name: Open Source Ecosystem
    title: Broad open source projects supporting s390x
    elements:
      - type: HorizontalCategory
        category: Linux Distributions
        rows: 6
        width: 200
        height: 300
        top: 0
        left: 0
        color: rgb(29,119,164)
        fit_width: true
      - type: HorizontalCategory
        category: Networking and Monitoring
        rows: 3
        width: 200
        height: 140
        top: 310
        left: 0
        color: rgb(19,105,73)
        fit_width: true
      - type: HorizontalCategory
        category: Cloud and Container Services
        rows: 9
        width: 200
        height: 450
        top: 0
        left: 210
        color: rgb(19,105,73)
        fit_width: true
      - type: HorizontalCategory
        category: Languages and Runtimes
        rows: 9
        width: 200
        height: 450
        top: 0
        left: 420
        color: rgb(19,105,73)
        fit_width: true
      - type: HorizontalCategory
        category: Devops and Automation
        cols: 3
        width: 200
        height: 300
        top: 0
        left: 630
        color: rgb(19,105,73)
        fit_width: true
      - type: HorizontalCategory
        category: Middleware
        rows: 3
        width: 200
        height: 140
        top: 310
        left: 630
        color: rgb(19,105,73)
        fit_width: true
      - type: HorizontalCategory
        category: Big Data, Observability, Analytics
        rows: 6
        width: 200
        height: 300
        top: 0
        left: 840
        color: rgb(19,105,73)
        fit_width: true
      - type: HorizontalCategory
        category: Databases
        rows: 3
        width: 200
        height: 140
        top: 310
        left: 840
        color: rgb(19,105,73)
        fit_width: true
    category: Broad Open Source
  fifth:
    tab_index: 3
    url: members
    name: Members
    title: Become an OMP member at www.openmainframeproject.org/about/join
    elements:
      - type: HorizontalCategory
        category: Platinum
        rows: 2
        width: 750
        height: 120
        top: 0
        left: 0
        color: rgb(40,40,40)
        fit_width: true
      - type: HorizontalCategory
        category: Silver
        rows: 4
        width: 750
        height: 220
        top: 110
        left: 0
        color: rgb(144,144,144)
        fit_width: true
      - type: HorizontalCategory
        category: Academic Institution
        rows: 4
        width: 750
        height: 220
        top: 320
        left: 0
        color: rgb(126,115,14)
        fit_width: true
      - type: HorizontalCategory
        category: Associate
        rows: 2
        width: 750
        height: 100
        top: 530
        left: 0
        color: rgb(126,115,14)
        fit_width: true
    category: Open Mainframe Project Member Company
test:
  header: Open Mainframe Project Interactive Landscape
  section: Graduated Open Mainframe Projects
  logo: zowe.svg
prerender:
  members: /card-mode?category=open-mainframe-project-member-company&grouping=category&embed=yes&style=borderless
  members-non-grouped: /card-mode?category=open-mainframe-project-member-company&grouping=no&embed=yes&style=borderless
  hosted-projects: /card-mode?project=hosted&embed=yes&style=borderless
  zowe-conformant: /card-mode?category=api-mediation-layer-zowe-v1%2Capp-framework-zowe-v1%2Ccli-zowe-v1&grouping=category&embed=yes&style=logo
  zowe-conformant-2019: /card-mode?category=api-mediation-layer-2019%2Capp-framework-2019%2Ccli-2019&grouping=category&embed=yes&style=logo
export:
  projects-hosted: card-mode?grouping=no&category=projects&project=hosted
  projects-hosted-by-stage: card-mode?category=projects&project=hosted
