name: Autocommit pull requests

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Automerge Pull Request if possible
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
          MERGE_LABELS: "automerge"
          MERGE_RETRY_SLEEP: 300000
          MERGE_METHOD: "squash"
      - name: Remove from general kanban board
        uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: OMP 2021 Q3
          column: To Do
          repo-token: ${{ secrets.YOUR_NEW_PERSONAL_TOKEN }}
          action: delete
