# This is a basic workflow to help you get started with Actions

name: Move new requests to the correct Open Mainframe Project Kanban Boards

on:
  issues:
    types: [opened, labeled, closed]
  pull_request_target:
    types: [opened, labeled, closed]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
    - name: Add to general kanban board
      uses: alex-page/github-project-automation-plus@v0.3.0
      if: |
        github.event.action == 'opened' && 
        ( github.event_name == 'issues' || github.event_name == 'pull_request_target' ) &&
        !contains(github.event.issue.labels.*.name,'automated-build')
      with:
        project: OMP 2021 Q3
        column: To Do
        repo-token: ${{ secrets.YOUR_NEW_PERSONAL_TOKEN }}
